#!/usr/bin/env python3

"""
This module contains a function that displays the number of documents in the collection school.
"""

import pymongo
import sys

def count_school_documents(db_name):
    """
    This function displays the number of documents in the collection school.
    """
    # Connect to the MongoDB instance
    client = pymongo.MongoClient("mongodb://localhost:27017/")

    # Access the database specified as a command-line option
    db = client[db_name]

    # Access the collection school
    school = db["school"]

    # Count the number of documents in the collection school
    count = school.count_documents({})

    # Print the number of documents in the collection school
    print("Number of documents in the collection school:", count)

if __name__ == "__main__":
    # Check if a database name was passed as a command-line option
    if len(sys.argv) != 2:
        print("Error: Please specify a database name")
        sys.exit(1)

    db_name = sys.argv[1]
    count_school_documents(db_name)
